---
#
# Ansible managed
#
repository:
  description: Install and configure snmpd on your system.
  homepage: https://robertdebock.nl/
  topics: snmpd, monitoring, system, ansible, molecule, tox, playbook
